INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (1, '49765', 'MARCIA', 'GUIMARAES');
INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (2, '99765', 'BERNARDO', 'JUAREZ');
INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (3, '789765', 'CRISTOVAO', 'BUARQUE');
INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (4, '987236', 'VENANCIO', 'LIMEIRA');
INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (5, '372649', 'CRISTIELE', 'CONSTATE');
INSERT INTO CUSTOMER (ID, DOCUMENT_CUSTOMER, FIRST_NAME_CUSTOMER, LAST_NAME_CUSTOMER) VALUES (6, '293716', 'DANIEL', 'LIMA');



INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (1,'83020000', 'RUA DR MANOEL RIBEIRO DE CAMPOS', 'SAN JOSE',1);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (2,'82040000', 'RUA MATO GROSSO DO SUL', 'SAN JHON',1);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (3,'83050000', 'RUA SAO BERALDINO', 'SAN CAMILO',1);

INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (4,'86020000', 'RUA DR MANOEL DOS PRAZERES','SAN GOMES',2);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (5,'87040000', 'RUA MASTODONTI', 'SAN JOAQUIM',2);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (6,'88050000', 'RUA SAO CRISTOPHER', 'SAN DOMINGOS',2);

INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (7,'88030000', 'RUA CAPITAO', 'SAN MIGUEL',3);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (8,'89040000', 'RUA MAJOR', 'SAN PEDRO',3);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (9,'90050000', 'RUA GENERAL', 'SAN MENEZES',3);

INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (10,'27485960', 'RUA CORONEL', 'SAN MARINO',4);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (11,'85749307', 'RUA TEN', 'SAN PETTER',4);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (12,'82746392', 'RUA SUB', 'SAN JOSEPH',4);

INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (13,'85858533', 'RUA SARGENTO', 'SAN PATRICK',5);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (14,'47859376', 'RUA SOLDADO', 'SAN PETRONE',5);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (15,'87392746', 'RUA CABO', 'SAN POLICARPIO',5);

INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (16,'62091837', 'RUA BOING', 'SAN AIRBUS',6);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (17,'87392762', 'RUA CRJ', 'SAN BOING',6);
INSERT INTO ADDRESS (ID, CEP_ADDRESS, LOGRADOURO_ADDRESS, CIDADE_ADDRESS, CUSTOMER_ID) VALUES (18,'37474747', 'RUA NEXT GENERATION', 'SAN OITOCENTOS',6);